# Generated by Django 3.1.3 on 2020-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genbank_query', models.CharField(max_length=500)),
                ('genbank_results', models.JSONField()),
                ('gbif_query', models.CharField(max_length=500)),
                ('gbif_results', models.JSONField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
