# Generated by Django 3.1.3 on 2020-11-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrun',
            name='gbif_query',
            field=models.JSONField(),
        ),
    ]
