# Generated by Django 3.1.3 on 2020-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201111_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrun',
            name='gbif_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchingrun',
            name='genbank_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
