# Generated by Django 3.1.3 on 2020-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201111_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingrun',
            old_name='genbank_query',
            new_name='ena_query',
        ),
        migrations.RenameField(
            model_name='matchingrun',
            old_name='genbank_results',
            new_name='ena_results',
        ),
        migrations.AddField(
            model_name='matchingrun',
            name='wikidata_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
