# Generated by Django 3.1.3 on 2020-11-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201111_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrun',
            name='suggested_matches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchingrun',
            name='validated_matches',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
